# Generated by Django 2.0.8 on 2018-12-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, default='images/no_image.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='message',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='opportunities.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/no_image.png', null=True, upload_to='images'),
        ),
    ]
